server:
  port: 8087

spring:
  application:
    name: authorization-server-example

security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess

logging.level.org.springframework.security: DEBUG
